# Configuração automática do datasource Prometheus no Grafana
# Este arquivo é carregado automaticamente quando o Grafana inicia

apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: "15s"
      queryTimeout: "60s"
      httpMethod: "GET"
    secureJsonData: {}
    version: 1

